# Generated by Django 2.2.7 on 2019-11-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('f_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('f_name', models.CharField(max_length=50)),
                ('f_phone', models.CharField(max_length=15)),
                ('f_address', models.CharField(max_length=250)),
                ('f_email', models.EmailField(max_length=50, unique=True)),
                ('f_password', models.CharField(max_length=50)),
                ('f_nid_no', models.CharField(max_length=25, unique=True)),
                ('f_land_amount', models.IntegerField()),
                ('f_farming_on', models.IntegerField()),
            ],
        ),
    ]
