# Generated by Django 2.2.7 on 2019-11-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=50)),
                ('crop_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('dist_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('num_of_upazilla', models.IntegerField()),
                ('num_of_union', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DC',
            fields=[
                ('dc_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('dc_name', models.CharField(max_length=50)),
                ('dc_phone', models.CharField(max_length=15)),
                ('dc_address', models.CharField(max_length=150)),
                ('dc_email', models.EmailField(max_length=50, unique=True)),
                ('dc_password', models.CharField(max_length=50)),
                ('dc_nid_no', models.CharField(max_length=25, unique=True)),
                ('dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC.District')),
            ],
        ),
    ]
