# Generated by Django 2.2.7 on 2019-11-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpChairman',
            fields=[
                ('upc_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('upc_name', models.CharField(max_length=50)),
                ('upc_phone', models.CharField(max_length=15)),
                ('upc_address', models.CharField(max_length=150)),
                ('upc_email', models.EmailField(max_length=50, unique=True)),
                ('upc_password', models.CharField(max_length=50)),
                ('upc_nid_no', models.CharField(max_length=25, unique=True)),
                ('dc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC.DC')),
            ],
        ),
        migrations.CreateModel(
            name='Upazilla',
            fields=[
                ('upz_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('upz_name', models.CharField(max_length=25)),
                ('num_of_union', models.IntegerField()),
                ('num_of_mill', models.IntegerField()),
                ('dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC.District')),
            ],
        ),
    ]
