# Generated by Django 2.2.7 on 2019-11-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UpChairman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upazilla',
            name='upz_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
