# Generated by Django 3.0b1 on 2019-11-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DC', '__first__'),
        ('Farmer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAgent',
            fields=[
                ('fa_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('fa_name', models.CharField(max_length=50)),
                ('fa_phone', models.CharField(max_length=15)),
                ('fa_address', models.CharField(max_length=250)),
                ('fa_email', models.EmailField(max_length=50, unique=True)),
                ('fa_password', models.CharField(max_length=50)),
                ('fa_nid_no', models.CharField(max_length=25, unique=True)),
                ('fa_farmer_under_obs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonReport',
            fields=[
                ('season_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('season_name', models.CharField(max_length=50)),
                ('field_size', models.CharField(max_length=5)),
                ('estimated_crop', models.IntegerField()),
                ('estimated_cost', models.FloatField()),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC.Crop')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalServey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyId', models.IntegerField()),
                ('areaOfFarmedLand', models.IntegerField()),
                ('farmedCrop', models.CharField(max_length=20)),
                ('cropType', models.CharField(max_length=10)),
                ('estimatedCrop', models.IntegerField()),
                ('farmingStartDate', models.DateField()),
                ('farmingEndDate', models.DateField()),
                ('fId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.Farmer')),
                ('seasonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FieldAgent.SeasonReport')),
            ],
        ),
    ]
