# Generated by Django 2.2.7 on 2019-11-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farmer', '0001_initial'),
        ('DC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAgent',
            fields=[
                ('fa_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('fa_name', models.CharField(max_length=50)),
                ('fa_phone', models.CharField(max_length=15)),
                ('fa_address', models.CharField(max_length=250)),
                ('fa_email', models.EmailField(max_length=50, unique=True)),
                ('fa_password', models.CharField(max_length=50)),
                ('fa_nid_no', models.CharField(max_length=25, unique=True)),
                ('fa_farmer_under_obs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonReport',
            fields=[
                ('season_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('season_name', models.CharField(max_length=50)),
                ('field_size', models.CharField(max_length=5)),
                ('estimated_crop', models.IntegerField()),
                ('estimated_cost', models.FloatField()),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DC.Crop')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.Farmer')),
            ],
        ),
    ]
